version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      - REPO_URI=185743266330.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started...
      - docker build -t $REPO_URI:$IMAGE_TAG .
  
  post_build:
    commands:
      - echo Build completed...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image definitions...
      - printf '[{"name":"brain-tasks-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
