version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-credentials:username
    DOCKERHUB_PASSWORD: dockerhub-credentials:password

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t aravindkumar18/brain-tasks-app:$CODEBUILD_BUILD_NUMBER .

  post_build:
    commands:
      - echo "Pushing image to Docker Hub"
      - docker push aravindkumar18/brain-tasks-app:$CODEBUILD_BUILD_NUMBER
      - echo "$CODEBUILD_BUILD_NUMBER" > imageTag.txt

artifacts:
  files:
    - imageTag.txt
