version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI and kubectl...
      - apt-get update -y
      - apt-get install -y unzip curl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-eks
      - kubectl get nodes

  build:
    commands:
      - echo Deploying Kubernetes manifests...
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

  post_build:
    commands:
      - echo Deployment complete.
