version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t aravindkumar18/brain-tasks-app:latest .

  post_build:
    commands:
      - echo "Pushing image to Docker Hub"
      - docker push aravindkumar18/brain-tasks-app:latest
