version: 0.2

env:
  variables:
    CLUSTER_NAME: "brain-tasks-eks"
    AWS_DEFAULT_REGION: "ap-south-1"

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
  pre_build:
    commands:
      - echo Configuring kubeconfig...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $CLUSTER_NAME
  build:
    commands:
      - echo Deploying Kubernetes manifests...
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
